on: [pull_request]

jobs:
  build-chain:
    runs-on: ubuntu-latest
    name: Build Pull Request
    steps:
    - uses: actions/checkout@v2
    - name: Build Chain
      id: build-chain
      uses: kiegroup/github-action-build-chain@master
      with:
        build-command: 
          mvn -e -nsu -Dfull -Pwildfly clean install -Prun-code-coverage  -Dcontainer.profile=wildfly -Dcontainer=wildfly -Dintegration-tests=true -Dmaven.test.failure.ignore=true -DjvmArgs="-Xms1g -Xmx4g"
          mvn -nsu generate-resources -Psonarcloud-analysis -DjvmArgs="-Xms1g -Xmx4g"
      env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          SONARCLOUD_TOKEN: "${{ secrets.SONARCLOUD_TOKEN }}"
